config/routes.rb
Rails.application.routes.draw do

  get 'inventory', to: 'inventory#index'

  namespace :inventory do
    resources :skus
  end

  resources :work_orders do
    resources :line_items, only: [:create, :edit]
  end

  root 'static#landing'

## Need routing for generating new line items on work order

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
module Inventory
  def self.table_name_prefix
    'inventory_'
  end
end
 

app/models/inventory/sku.rb
class Inventory::SKU < ApplicationRecord
  has_many :line_item, through: :work_orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :inventory_sku, class_name: "Inventory::SKU"
  belongs_to :work_order
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  has_many :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ###################################
  ##   I love you, Daeden Stoker   ##
  ###################################
  protect_from_forgery with: :exception
end

app/controllers/inventory/skus_controller.rb
class Inventory::SKUsController < ApplicationController
  before_action :set_inventory_sku, only: [:show, :edit, :update, :destroy]

  # GET /inventory/skus
  # GET /inventory/skus.json
  def index
    @inventory_skus = Inventory::SKU.all
  end

  # GET /inventory/skus/1
  # GET /inventory/skus/1.json
  def show
  end

  # GET /inventory/skus/new
  def new
    @inventory_sku = Inventory::SKU.new
  end

  # GET /inventory/skus/1/edit
  def edit
  end

  # POST /inventory/skus
  # POST /inventory/skus.json
  def create
    @inventory_sku = Inventory::SKU.new(inventory_sku_params)

    respond_to do |format|
      if @inventory_sku.save
        format.html { redirect_to @inventory_sku, notice: 'SKU was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_sku }
      else
        format.html { render :new }
        format.json { render json: @inventory_sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory/skus/1
  # PATCH/PUT /inventory/skus/1.json
  def update
    respond_to do |format|
      if @inventory_sku.update(inventory_sku_params)
        format.html { redirect_to @inventory_sku, notice: 'SKU was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_sku }
      else
        format.html { render :edit }
        format.json { render json: @inventory_sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory/skus/1
  # DELETE /inventory/skus/1.json
  def destroy
    @inventory_sku.destroy
    respond_to do |format|
      format.html { redirect_to inventory_skus_url, notice: 'SKU was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_sku
      @inventory_sku = Inventory::SKU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_sku_params
      params.require(:inventory_sku).permit(:descriptive_id)
    end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController

  def index

  end

end 

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, except: [:create]


  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create

    # When JSON Payload is needed, this will need to be refactored to respond to with JSON!
    
    
    @work_order = WorkOrder.find(params[:work_order_id])
    @line_item = @work_order.line_items.build(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @work_order, notice: 'added line item' }
        format.js
      else
        format.html { redirect_to @work_order }
        format.js { render js: "alert('#{@line_item.errors.inspect}');" }
        ## TODO: Proper error handling.
      end
    end

  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    # Need to work on this!!!!
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:line_item, :description, :quantity, :price_adjustment, :work_order_id, :inventory_sku_id)
    end
end 

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def landing
    ## User not logged in, root page
    ## Page editable in settings
  end
  
end 

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  # GET /work_orders
  # GET /work_orders.json
  def index
    @work_orders = WorkOrder.all
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
    @line_items = @work_order.line_items
    @new_line_item = @work_order.line_items.new
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
 end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: 'Work order was successfully created.' }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1
  # PATCH/PUT /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order.destroy
    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: 'Work order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_order_params
      params.require(:work_order).permit(:started_on, :notes, :status)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory/skus_helper.rb
module Inventory::SKUsHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/inventory/index.html.erb
<h1>Inventory</h1>

app/views/inventory/skus/_form.html.erb
<%= form_with(model: inventory_sku, local: true) do |form| %>
  <% if inventory_sku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_sku.errors.count, "error") %> prohibited this inventory_sku from being saved:</h2>

      <ul>
      <% inventory_sku.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descriptive_id %>
    <%= form.text_field :descriptive_id, id: :sku_descriptive_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory/skus/edit.html.erb
<h1>Editing Inventory Sku</h1>

<%= render 'form', inventory_sku: @inventory_sku %>

<%= link_to 'Show', @inventory_sku %> |
<%= link_to 'Back', inventory_skus_path %>

app/views/inventory/skus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory SKUs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_skus.each do |inventory_sku| %>
      <tr>
        <td><%= inventory_sku.descriptive_id %></td>
        <td><%= link_to 'Show', inventory_sku %></td>
        <td><%= link_to 'Edit', edit_inventory_sku_path(inventory_sku) %></td>
        <td><%= link_to 'Destroy', inventory_sku, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory Sku', new_inventory_sku_path %>

app/views/inventory/skus/new.html.erb
<h1>New Inventory Sku</h1>

<%= render 'form', inventory_sku: @inventory_sku %>

<%= link_to 'Back', inventory_skus_path %>

app/views/inventory/skus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inventory_sku_path(@inventory_sku) %> |
<%= link_to 'Back', inventory_skus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandalz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/line_items/_add_line_item.html.erb
<%= form_for([@work_order, @new_line_item], remote: true) do |form| %>

    <%= form.collection_select(:inventory_sku_id, Inventory::SKU.all, :id, :descriptive_id) %>

    <%= form.text_field :description, id: :line_item_description %>

    <%= form.number_field :quantity, id: :line_item_quantity %>

    <%= form.hidden_field :work_order_id, id: :work_order_id, value: wo.id %>

  <div class="actions">
    <%= form.submit "New Item" %>
  </div>
  
<% end %>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, remote: true) do |form| %>

    <%= form.collection_select(:work_order_id, WorkOrder.all, :id, :id) %> <br />
    <%= form.collection_select(:inventory_sku_id, Inventory::SKU.all, :id, :descriptive_id) %> <br />


    <%= form.text_area :description, id: :line_item_description %>

    <%= form.number_field :quantity, id: :line_item_quantity %>


  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/line_items/create.js.erb
alert("line_items#_controller#Create / views/line_items/create.js.erb");

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/work_orders/_form.html.erb
<%= form_with(model: work_order, local: true) do |form| %>
  <% if work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% work_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :started_on %>
    <%= form.date_select :started_on, id: :work_order_started_on %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :work_order_notes %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select([['Closed','0'],['Awaiting Client Contact','1'],['Currently Active','2']], work_order.status) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/work_orders/edit.html.erb
<h1>Editing Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Orders</h1>

<table>
  <thead>
    <tr>
      <th>Started on</th>
      <th>Closed on</th>
      <th>Notes</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_orders.each do |work_order| %>
      <tr>
        <td><%= work_order.started_on %></td>
        <td><%= work_order.closed_on %></td>
        <td><%= work_order.notes %></td>
        <td><%= work_order.status %></td>
        <td><%= link_to 'Show', work_order %></td>
        <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
        <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Order', new_work_order_path %>

app/views/work_orders/new.html.erb
<h1>New Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Started on:</strong>
  <%= @work_order.started_on %>
</p>

<p>
  <strong>Closed on:</strong>
  <%= @work_order.closed_on %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @work_order.notes %>
</p>

<p>
  <%= form_with(model: @work_order, local: true) do |form| %>

  <div class="field">
    <strong><%= form.label :status %></strong>
    <%= form.select :status, options_for_select([['Closed','0'],['Awaiting Client Contact','1'],['Currently Active','2']], @work_order.status) %>

    <%= form.submit "Update Status" %>
<% end %>
</div>

<%= @work_order.line_items.each do |li| %>
  <p> <%= li.description %> </p>
  <% end %>

<%= render 'line_items/add_line_item', wo: @work_order %>

</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>